apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: auth
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30007
