apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  uri: mongodb://kjw:1234@mongo-mongodb.default.svc.cluster.local:27017/auth
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-key
type: Opaque
stringData:
  key1: 4@+4if$5@)k-=4e)ehlt&s8!*24y7pl!pz)hwtzv5e3i^@_t10
  key2: _%o$eji=4v88s&-sqrq5-sx!6*xvd_8_v8zp4)iodbwx_#x%gw
